/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotingRouteImport } from './routes/voting'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as IndexRouteImport } from './routes/index'

const VotingRoute = VotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explainability': typeof ExplainabilityRoute
  '/policy': typeof PolicyRoute
  '/transparency': typeof TransparencyRoute
  '/voting': typeof VotingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explainability': typeof ExplainabilityRoute
  '/policy': typeof PolicyRoute
  '/transparency': typeof TransparencyRoute
  '/voting': typeof VotingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explainability': typeof ExplainabilityRoute
  '/policy': typeof PolicyRoute
  '/transparency': typeof TransparencyRoute
  '/voting': typeof VotingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explainability' | '/policy' | '/transparency' | '/voting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explainability' | '/policy' | '/transparency' | '/voting'
  id:
    | '__root__'
    | '/'
    | '/explainability'
    | '/policy'
    | '/transparency'
    | '/voting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  PolicyRoute: typeof PolicyRoute
  TransparencyRoute: typeof TransparencyRoute
  VotingRoute: typeof VotingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voting': {
      id: '/voting'
      path: '/voting'
      fullPath: '/voting'
      preLoaderRoute: typeof VotingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  PolicyRoute: PolicyRoute,
  TransparencyRoute: TransparencyRoute,
  VotingRoute: VotingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
